-- AlterTable
ALTER TABLE "putaway_items" ADD COLUMN "actual_qty" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "quality_issue" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "qty_issue" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "remaining_qty" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "bin_id" TEXT;

-- AddForeignKey
ALTER TABLE "putaway_items" ADD CONSTRAINT "putaway_items_bin_id_fkey" FOREIGN KEY ("bin_id") REFERENCES "bins"("id") ON DELETE SET NULL ON UPDATE CASCADE;
